#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

 **Please enter your student number in the cell below**

22380996

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [62]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [63]:
def symmetric(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]): 
            if M[i][j] != M[j][i]:
                return "Not Symmetric"
    return "Symmetric"

Test your function on the two matrices below

In [64]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [65]:
print(symmetric(SymMatrix))

Symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [66]:
def MatTranspose(M):
    transpose = np.zeros([M.shape[0],M.shape[1]])
    for i in range(M.shape[0]):
        for j in range(M.shape[1]): 
            transpose[j][i]=M[i][j]
    return transpose
    

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [67]:
A = np.random.rand(6,6)
AT = MatTranspose(A)
if (A == AT).all():
    print("Equal")
else:
    print("Not Equal")

Not Equal


In [68]:
ATT = MatTranspose(AT)
print("A^T^T-A=\n", ATT-A)

A^T^T-A=
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [69]:
def MaxMatrix(M):
    max  = M[0][0]
    for i in range(M.shape[0]):
        for j in range(M.shape[1]): 
            if (M[i][j] > max):
                max = M[i][j]
    return max

Check your result by comparing to `np.max(A)` for the below random matrix

In [70]:
A = np.random.rand(4,5)

print(A)
print(MaxMatrix(A))

[[0.84255662 0.5592733  0.37750098 0.69680674 0.5279357 ]
 [0.43027423 0.95657353 0.63082466 0.81676389 0.82936909]
 [0.91045001 0.64653941 0.03888016 0.80596149 0.87899017]
 [0.87725395 0.68898512 0.03569798 0.04489877 0.81747407]]
0.9565735292781209


Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [71]:
A = np.random.rand(3,4)


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [72]:
A = np.random.rand(3,4)



Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [73]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [74]:
# Answer here


Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [75]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [76]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

Check your answers against Numpy's results from `la.eig(A)`

## Submitting your assignment

Commit your notebook to git and push it to GitHub. Your assignment will be graded directly from GitHub.